# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.BOOST_GP_MCMC_cpp <- function(Y, dist, nei, s, iter, burn, update_prop, init_b_sigma, init_h) {
    .Call(`_boost_BOOST_GP_MCMC_cpp`, Y, dist, nei, s, iter, burn, update_prop, init_b_sigma, init_h)
}

.BOOST_Ising_MCMC_cpp <- function(p, A, mean_omega0, sigma_omega0, mean_theta, sigma_theta, n_iter, burn, M, tau, omega0_init, theta_init) {
    .Call(`_boost_BOOST_Ising_MCMC_cpp`, p, A, mean_omega0, sigma_omega0, mean_theta, sigma_theta, n_iter, burn, M, tau, omega0_init, theta_init)
}

